import type { Dict } from './types';

const nl: Dict = {
  meta: {
    title: 'Websites, webshops en digitale menukaarten | Rafetov.com',
    description: 'Bedrijfswebsites vanaf €580, webshops vanaf €700, Meta-advertenties en SEO. Gratis advies via telefoon of Google Meet en een persoonlijke videoanalyse van uw website.',
    privacyTitle: 'Privacybeleid | Rafetov.com', privacyDescription: 'Hoe Dzhan Rafetov (BULSTAT 181648949) persoonsgegevens verwerkt: doeleinden, rechtsgrond, bewaartermijnen en uw rechten.',
    legalTitle: 'Juridische informatie | Rafetov.com', legalDescription: 'Juridische informatie over rafetov.com, Dzhan Rafetov, contactgegevens en gebruiksvoorwaarden.',
  },
  header: { menu:'Menu', ctaButton:'Gratis gesprek aanvragen', call:'Bellen', callAria:'Bel ons: +359 897 758 062', langAria:'Taal kiezen', links:{hero:'Home',services:'Diensten',work:'Projecten',process:'Werkwijze',blog:'Blog',contact:'Contact'} },
  hero: { badge:'Open voor projecten',h1a:'Een website die',h1b:'klanten oplevert.',sub1:'Websites, SEO en advertenties voor uw bedrijf —',sub2:'zodat mensen u vinden, vertrouwen en contact opnemen.',chips:{site:'Website',shop:'Webshop',ads:'Advertenties'},cta:'Gratis gesprek aanvragen',cta2:'Projecten bekijken',micro:'Gratis advies · Telefoon of Google Meet · Duidelijke offerte',clientsLabel:'Klanten in 6 landen' },
  countries:{BG:'Bulgarije',DE:'Duitsland',BE:'België',GB:'Verenigd Koninkrijk',ES:'Spanje',NO:'Noorwegen'},
  services: { eyebrow:'diensten',h2a:'Van idee',h2b:'naar resultaat',sub:'Zonder vakjargon. We bouwen oplossingen die werken en eenvoudig te gebruiken zijn.',
    items:{
      site:{label:'Website',title:'Een website voor uw bedrijf',text:'Een snelle, overzichtelijke website die duidelijk maakt wie u bent en hoe u helpt. Geschikt voor mobiel en voorbereid op Google.',points:['Meerdere talen mogelijk','Duidelijke kop en zichtbare contactknoppen','Kaart, telefoonnummer en kort formulier'],price:'Vanaf €580',priceNote:'vaste offerte vóór de start'},
      shop:{label:'Webshop',title:'Webshop',text:'Een webshop waarmee klanten eenvoudig bestellen op hun telefoon of computer.',points:['Betalen met kaart of overschrijving','Kortingscodes en acties','Verzending en koppelingen met bezorgdiensten'],price:'Vanaf €700',priceNote:'vaste offerte vóór de start'},
      ads:{label:'Advertenties',title:'Google- en Facebook-advertenties',text:'Bereik de juiste mensen op Facebook, Instagram en Google. Het doel: aanvragen en verkoop.',points:['Facebook- en Instagram-campagnes','Google Search en display-advertenties','Optimalisatie en rapportage'],price:'Offerte na een gesprek',priceNote:'beheer en advertentiebudget apart'},
      menu:{label:'Menukaart',title:'Digitale menukaart',text:'Gasten scannen een QR-code en bekijken uw menukaart op hun telefoon. Altijd actueel, zonder opnieuw te drukken.',points:['Foto’s, categorieën en allergenen','Eenvoudig aanpassen via uw telefoon','QR-codes voor de tafels'],price:'Offerte na een gesprek',priceNote:'eenmalig, inclusief QR-codes'},
    },more:'Meer informatie',cta:'Neem contact op',cta2:'Projecten bekijken',micro:'Snelle reactie · Geen spam',pricePromise:'Een vaste prijs die we vooraf afspreken. Geen verborgen kosten.',priceLink:'Wat kost een website?',
  },
  care:{eyebrow:'begeleiding',h2a:'U runt uw bedrijf.',h2b:'Wij regelen de rest.',sub:'Hosting, instellingen en onderhoud volgens de afspraken in uw offerte.',items:{hosting:{title:'Hosting volgens afspraak',text:'Elke website heeft hosting nodig. De voorwaarden en eventuele kosten staan in uw offerte.'},support:{title:'Ondersteuning na de start',text:'Werkt iets niet of wilt u een wijziging? Stuur ons een bericht of bel ons.'},training:{title:'Uitleg in gewone taal',text:'We laten u zien hoe u zelf foto’s, prijzen en teksten aanpast.'},price:{title:'Vooraf een duidelijke prijs',text:'U weet vóór de start wat het kost en wat inbegrepen is.'}},cta:'Gratis advies',micro:'Gratis gesprek · Vrijblijvend · Duidelijke uitleg'},
  work:{eyebrow:'projecten',h2a:'Echte bedrijven.',h2b:'Concrete oplossingen.',sub:'Bekijk hoe onze projecten diensten presenteren, reserveringen vereenvoudigen en aanvragen verzamelen. Elke website is live te bekijken.',all:'Alle',tags:{site:'Website',shop:'Webshop',menu:'Digitale menukaart'},viewSite:'Website bekijken',viewMenu:'Menukaart bekijken',titles:{'opaka-fits':'Opaka Fits Complex','pet-zvezdi':'5 Zvezdi Exotics','hotel-fenix':'Hotel Fenix','mig-group':'MIG Engineering Group'},projects:{
    'chef-resat-site':'Website voor restaurant Chef Resat met aandacht voor de sfeer, keuken en praktische informatie.',vulcho:'Online slagerij met loyaliteitsprogramma, kortingscodes, vouchers, AI-recepten en beheer van bestellingen en voorraad.',zirve1:'Officiële webshop voor Zirve1-metaaldetectoren met bestellen en levering in Europa.','emis-cleaning':'Website voor een schoonmaakbedrijf in Londen met online boekingen.',santander:'Website voor een taxidienst in Santander, Spanje, met een snel reserveringsformulier.',beca:'Bedrijfswebsite voor een verhuis- en schoonmaakbedrijf in München.','amalfi-menu':'Digitale menukaart voor restaurant Amalfi in Elverum, Noorwegen, in het Noors en Engels.','chef-resat-menu':'Digitale menukaart voor Chef Resat in het Bulgaars, Turks en Engels.','pancetita-menu':'Digitale menukaart voor Pizza Pancetita in Oslo in het Noors en Engels.','abi-studio':'Website voor een beautystudio in Varna met behandelingen en prijzen.',metesso:'Website voor een meubelshowroom in Plovdiv met een collectiecatalogus.','opaka-fits':'Website voor een complex met zwembad, restaurant en gastenkamers, digitale menukaart en reserveringsaanvragen.',taupe:'Website voor een vastgoedproject in Gorubljane met projectpresentatie en aanvraagformulier.','azteca-site':'Webshop voor premium sigaren en aanstekers.','dudo-group':'Website voor een bouwmarkt met een catalogus van bouw- en renovatiematerialen.','het-pitta-loft':'Website voor een restaurant in Antwerpen met reserveringssysteem, e-mailmeldingen en reserveringsbeheer.','pet-zvezdi':'Website voor een auto-importeur met beschikbare modellen en een aanvraagformulier.','hh-edelstahl':'Website voor een werkplaats voor roestvrij staal en ventilatiesystemen in Berlijn.',primasell:'Website voor drukwerk, branding en gepersonaliseerde geschenken.',szo:'Webshop voor beveiligingssystemen met online bestellingen en installatieaanvragen.','24tours':'Reisplatform met online boekingen, betalingen, cadeaubonnen en kortingscodes.','hustle-clothing':'Kledingwebshop met beheer van producten, kortingscodes en verkoop.',shop4home:'Webshop voor huishoudelijke artikelen met eenvoudig bestel- en productbeheer.','korn-metal':'Bedrijfswebsite voor metaalhandel en metaalconstructies met catalogus, portfolio en aanvragen.','hotel-fenix':'Website voor een familiehotel in Chepelare met kamers, restaurant en boekingsaanvragen.',slapfight:'Platform voor online ticketverkoop voor evenementen.','mig-group':'Website voor landmeetdiensten: kadaster, uitzetten, drone-opmetingen en 3D-laserscanning.','innenausbau-ahmedov':'Website voor een afwerkingsbedrijf in Hanau met projecten en offerteaanvragen.','nn-bau':'Website voor waterdichting, renovatie, gipsplaatwerk en sloop in Duisburg.','alpha-reiniging':'Website voor Alpha Reiniging in Gent: ramen, daken, gevels en zonnepanelen, met diensten en offerteaanvragen.',
  }},
  reviews:{eyebrow:'beoordelingen',h2a:'Wat onze klanten',h2b:'over ons zeggen.',sub:'Echte Google-beoordelingen, ongewijzigd en in de oorspronkelijke taal.',count:'{n} beoordelingen op Google',viewAll:'Alle beoordelingen op Google',original:'Origineel in het',langs:{bg:'Bulgaars',de:'Duits',tr:'Turks',es:'Spaans',no:'Noors',nl:'Nederlands',en:'Engels'},tags:{repeat:'Terugkerende klant',twoSites:'2 websites',rescue:'Opnieuw opgebouwd',hands:'Minimale inzet van de klant',deadline:'Korte deadline',shop:'Website + webshop'},prev:'Vorige beoordeling',next:'Volgende beoordeling',more:'Volledige beoordeling lezen',less:'Minder tonen',showTranslation:'Vertaling tonen',showOriginal:'Origineel tonen',translated:'Vertaling',showMore:'Nog {n} beoordelingen tonen',ctaTitle:'De volgende beoordeling kan van u zijn.',cta:'Gratis gesprek aanvragen'},
  process:{eyebrow:'werkwijze',h2a:'Zo werken we —',h2b:'kort en duidelijk',sub:'4 stappen, zonder omwegen. U levert ideeën en materiaal — wij regelen de rest.',stepLabel:'Stap',steps:[
    {title:'Kort gesprek',time:'20 min',text:'We bespreken uw bedrijf, doelen en budget via telefoon of Google Meet. Het advies is gratis.',bullets:['Geen voorbereiding nodig','Telefonisch of online']},
    {title:'Plan en offerte',time:'Na het gesprek',text:'U ontvangt een schriftelijke offerte met de werkzaamheden, prijs, planning, betalingsvoorwaarden en terugkerende kosten. We starten na akkoord en aanbetaling.',bullets:['Duidelijke stappen','Realistische planning']},
    {title:'Realisatie',time:'Afhankelijk van de omvang',text:'Ontwerp, inhoud en instellingen. U ziet de website vóór de lancering en geeft uw feedback.',bullets:['Geschikt voor mobiel','Vindbaar in Google']},
    {title:'Lancering en groei',time:'klaar 🚀',text:'We zetten de website live en blijven beschikbaar. Advertenties en uitbreidingen zijn mogelijk op aanvraag.',bullets:['Hosting passend bij het project','Ondersteuning na de start']},
  ],faqEyebrow:'veelgestelde vragen',faq:[
    {q:'Wat kost een website?',a:'Bedrijfswebsite: €580–2.300. Webshop: vanaf €700. Na een gesprek bepalen we de omvang en sturen we een vaste offerte. Complexe projecten krijgen een offerte op maat.'},
    {q:'Ik weet niets van websites en techniek — is dat een probleem?',a:'Helemaal niet. U vertelt ons over uw bedrijf, wij regelen de rest en leggen alles uit in gewone taal. We laten u ook zien hoe u de website zelf gebruikt.'},
    {q:'Wat gebeurt er na de lancering?',a:'We blijven beschikbaar. Ondersteuning, hosting en kosten voor extra wijzigingen worden in uw offerte beschreven.'},
    {q:'Hoe lang duurt het?',a:'Een website duurt ongeveer 1–3 weken, afhankelijk van de omvang en inhoud. Een webshop ongeveer 2–4 weken. De exacte planning staat in de offerte.'},
    {q:'Wat heeft u van mij nodig?',a:'Een korte beschrijving van uw bedrijf en doelen, een logo en foto’s als u die heeft, en iemand die feedback kan geven. Wij regelen de rest.'},
    {q:'Ik heb al een website — kunt u die vernieuwen?',a:'Ja. We nemen de inhoud over, verbeteren de structuur, snelheid en vindbaarheid in Google.'},
  ],cta:'Gratis gesprek aanvragen',cta2:'Echte projecten bekijken',micro:'Gratis advies · Telefoon of Google Meet · Duidelijke offerte'},
  contact:{eyebrow:'contact',h2a:'Laten we praten over',h2b:'uw bedrijf.',sub:'Vertel ons wat u wilt verbeteren. We stellen een passende oplossing voor en leggen uit waarvoor u betaalt.',statusTitle:'Beschikbaar voor nieuwe projecten',statusSub:'Reactie binnen 24 uur, meestal sneller',items:{phone:{label:'Telefoon',sub:'Bel ons rechtstreeks'},whatsapp:{label:'WhatsApp',value:'Stuur ons een WhatsApp-bericht',sub:'De snelste manier om ons te bereiken'},email:{label:'E-mail',sub:'Reactie binnen 24 uur'},location:{label:'Samenwerking',value:'We werken op afstand',sub:'We werken online voor klanten wereldwijd'}},formTitle:'Een aanvraag versturen',formSub:'Vul het formulier in — we reageren snel.',name:'Naam',namePlaceholder:'Uw naam',phone:'Telefoon',phonePlaceholder:'+31 6 1234 5678',phoneInvalid:'Vul een geldig telefoonnummer in, bijvoorbeeld +31 6 1234 5678.',email:'E-mail (optioneel)',emailPlaceholder:'naam@gmail.com',service:'Dienst (optioneel)',servicePlaceholder:'Kies een dienst',options:{site:'Website',shop:'Webshop',menu:'Digitale menukaart',ads:'Advertenties (Google / Facebook)',other:'Anders / Nog niet zeker'},message:'Bericht (optioneel)',messagePlaceholder:'Bijvoorbeeld: ik heb een restaurant en wil een website met menukaart en reserveringen.',send:'Aanvraag versturen',sending:'Versturen...',successTitle:'We hebben uw bericht ontvangen!',successSub:'We reageren binnen 24 uur.',hurry:'Heeft u haast?',newInquiry:'Nog een aanvraag versturen',micro:'Geen spam · Reactie binnen 24 uur · Liever praten?',call:'Bel ons',consent:'Door deze aanvraag te versturen bevestigt u dat u kennis heeft genomen van het',consentLink:'Privacybeleid',errorSubject:'Aanvraag via de website',sendByEmail:'Versturen via e-mail',sendByWhatsapp:'Versturen via WhatsApp',error:'Versturen is mislukt. Probeer opnieuw of bel ons op'},
  footer:{tagline:'Websites en webshops die klanten opleveren.',accepting:'Beschikbaar voor nieuwe projecten',navTitle:'Navigatie',contactTitle:'Contact',privacy:'Privacybeleid',legal:'Juridische informatie',rights:'Alle rechten voorbehouden.',design1:'Design dat',design2:'werkt'},
  mobileBar:{cta:'Gratis gesprek',aria:'Naar het aanvraagformulier'},whatsapp:{aria:'Stuur ons een WhatsApp-bericht',text:'Hallo! Ik ben geïnteresseerd in een website.'},
  legal:{updated:'Laatst bijgewerkt',bulgarianOnly:'Dit document is gepubliceerd in het Bulgaars. Die versie is juridisch bindend. Heeft u vragen? Neem contact op via business@rafetov.com.'},
  blog:{metaTitle:'Blog: advies over websites en webshops | Rafetov.com',metaDescription:'Praktische artikelen voor ondernemers over websites, webshops en digitale menukaarten.',eyebrow:'blog',title:'Handig voor uw bedrijf',sub:'Praktische artikelen voor ondernemers. De artikelen zijn beschikbaar in het Engels.',readMore:'Lees in het Engels',minRead:'min leestijd',allPosts:'Alle artikelen',backToBlog:'Terug naar de blog',teaserTitle:'Uit de blog',teaserSub:'Antwoorden op veelgestelde vragen — artikelen in het Engels.',related:'Meer over dit onderwerp',ctaTitle:'Wilt u een website die klanten oplevert?',ctaText:'Gratis advies via telefoon of Google Meet, gevolgd door een duidelijk plan en een vaste offerte.',ctaButton:'Gratis advies',tags:{site:'Website',shop:'Webshop',menu:'Digitale menukaart',general:'Advies'},photoCredit:'Foto: Unsplash',notFoundTitle:'Pagina niet gevonden',notFoundText:'Het adres klopt niet of de pagina is verplaatst.',notFoundHome:'Terug naar de homepage'},
  service:{eyebrow:'dienst',includes:'Wat is inbegrepen',forWhom:'Voor wie',process:'Zo werkt het',projects:'Onze projecten',allProjects:'Alle projecten',faq:'Veelgestelde vragen',related:'Meer informatie',allServices:'Alle diensten',ctaTitle:'Klaar om te beginnen?',ctaText:'Gratis advies via telefoon of Google Meet, gevolgd door een duidelijk plan en een vaste offerte.',ctaButton:'Gratis gesprek aanvragen'},loader:'Laden',
};
export default nl;
