import type { ServiceContent, ServiceId } from './index';
export const dutchServices: Record<ServiceId, ServiceContent> = {
  site: {
    slug:'website-laten-maken',metaTitle:'Bedrijfswebsite laten maken vanaf € 580 | Rafetov.com',metaDescription:'Een snelle, mobiele bedrijfswebsite met een duidelijk ontwerp en aanvraagformulier. Vaste offerte na gratis advies.',title:'Een website die aanvragen oplevert',intro:'Een website die duidelijk laat zien wie u bent en hoe u helpt, snel laadt op mobiel en voorbereid is op Google. Een ontwerp voor uw bedrijf met heldere afspraken over hosting.',priceLine:'Bedrijfswebsite: € 580–2.300 afhankelijk van de omvang. Vaste offerte na gratis advies via telefoon of Google Meet.',
    includes:['Ontwerp op maat voor uw bedrijf','Geschikt voor telefoon, tablet en computer','Technische SEO-basis en snelle laadtijd','Aanvraagformulier en zichtbare contactknoppen','Meerdere talen mogelijk volgens offerte','Hosting volgens afgesproken voorwaarden'],
    forWhom:['Dienstverleners en lokale bedrijven','Restaurants en hotels','Bedrijven met internationale klanten','Bedrijven die hun bestaande website willen vernieuwen'],
    faq:[{q:'Wat kost een website?',a:'Vanaf € 580. De uiteindelijke prijs hangt af van de inhoud, talen en functies. U ontvangt vooraf een vaste offerte.'},{q:'Kan ik zelf teksten en foto’s aanpassen?',a:'We bespreken welk beheer u nodig heeft en laten zien hoe u de afgesproken functies gebruikt.'},{q:'Hoe lang duurt het?',a:'Meestal 1–3 weken, afhankelijk van de omvang en de beschikbare inhoud. De planning staat in de offerte.'}],
  },
  shop:{slug:'webshop-laten-maken',metaTitle:'Webshop laten maken vanaf € 700 | Rafetov.com',metaDescription:'Een webshop met productcatalogus, betalingen en verzending afgestemd op uw bedrijf. Vaste offerte na een gesprek.',title:'Een webshop waarmee klanten eenvoudig bestellen',intro:'Een overzichtelijke webshop voor mobiel en computer. Producten, betalingen en levering worden afgestemd op uw bedrijf en uw klanten.',priceLine:'Webshop: vanaf € 700, afhankelijk van de catalogus en koppelingen. Complexe projecten krijgen een offerte op maat.',includes:['Productcatalogus met categorieën en filters','Productpagina’s met foto’s en beschrijvingen','Winkelwagen en eenvoudig afrekenen','Betaalmethoden zoals Bancontact, kaart of overschrijving','Verzending en koppelingen met bezorgdiensten','Beheer van producten en bestellingen'],forWhom:['Winkels die ook online willen verkopen','Merken met een eigen productlijn','Bedrijven met een bestaande webshop die beter moet werken','Verkopers met klanten in meerdere landen'],faq:[{q:'Wat kost een webshop?',a:'Vanaf € 700. Het aantal producten, de betaalmethoden en koppelingen bepalen de uiteindelijke offerte.'},{q:'Kan ik zelf producten toevoegen?',a:'Ja, we voorzien productbeheer en laten u zien hoe u het gebruikt.'},{q:'Welke betalingen en verzending zijn mogelijk?',a:'We kiezen samen passende betaalmethoden en bezorgdiensten. Externe kosten en voorwaarden staan apart in de offerte.'}]},
  menu:{slug:'digitale-menukaart',metaTitle:'Digitale menukaart voor restaurants | Rafetov.com',metaDescription:'Een actuele digitale menukaart met QR-codes, foto’s, categorieën en allergenen voor uw restaurant.',title:'Uw menukaart op de telefoon van uw gasten',intro:'Gasten scannen een QR-code en bekijken uw menukaart zonder een app te installeren. Prijzen en gerechten zijn eenvoudig aan te passen.',priceLine:'Een vaste offerte na een gesprek over uw menukaart, talen en gewenste functies.',includes:['Menukaart met duidelijke categorieën','Foto’s en omschrijvingen van gerechten','Prijzen en allergenen','Meerdere talen volgens afspraak','QR-codes voor uw tafels','Eenvoudig aanpassen van de inhoud'],forWhom:['Restaurants en cafés','Hotels met een restaurant','Bars en seizoenszaken','Zaken met internationale gasten'],faq:[{q:'Moeten gasten een app installeren?',a:'Nee. De QR-code opent de menukaart rechtstreeks in de browser.'},{q:'Kan ik prijzen zelf wijzigen?',a:'Ja, we laten u zien hoe u de inhoud bijwerkt.'},{q:'Kan de menukaart in meerdere talen?',a:'Ja. We spreken vooraf de talen en de benodigde vertalingen af.'}]},
  ads:{slug:'online-advertenties',metaTitle:'Meta- en Google-advertenties voor uw bedrijf | Rafetov.com',metaDescription:'Online advertenties gericht op aanvragen en verkoop. Duidelijke afspraken over inrichting, beheer en advertentiebudget.',title:'Advertenties die de juiste mensen bereiken',intro:'We bespreken uw doelen, doelgroep en budget en kiezen passende campagnes voor Facebook, Instagram of Google.',priceLine:'Meta-advertenties: € 70 voor inrichting; € 100–200 per maand voor beheer binnen de afgesproken omvang. Advertentiebudget apart. Google Ads na overleg.',includes:['Doelgroep en campagnedoel bepalen','Advertentieaccounts en metingen instellen','Campagnes op Facebook en Instagram','Google Ads volgens apart plan','Advertentievarianten met uw materiaal','Optimalisatie en rapportage'],forWhom:['Bedrijven die meer aanvragen willen','Nieuwe restaurants en winkels','Dienstverleners met een duidelijk aanbod','Webshops met producten waar vraag naar is'],faq:[{q:'Welk budget heb ik nodig?',a:'Dat hangt af van uw dienst, doelgroep en regio. We bespreken vooraf of advertenties zinvol zijn en welk budget past.'},{q:'Wanneer zie ik resultaat?',a:'Dat verschilt per campagne en markt. We beoordelen de resultaten en sturen bij; verkoop en aanvragen zijn niet gegarandeerd.'},{q:'Kan ik stoppen?',a:'De afspraken over looptijd en opzegging staan in de offerte. Uw advertentieaccounts blijven van u.'}]},
};
