import type { CountryCode, WorkTag } from "../i18n/types";

export type Project = {
  id: string;
  tag: WorkTag;
  title: string;
  img: string;
  href?: string;
  country?: CountryCode;
};

export const PROJECTS: Project[] = [
  {
    id: "chef-resat-site",
    tag: "site",
    title: "Chef Resat",
    img: "/work/rft.webp",
    href: "https://www.chefresatsofya.com/",
    country: "BG",
  },
  {
    id: "vulcho",
    tag: "shop",
    title: "Vulcho.bg",
    img: "/work/valchoph.webp",
    href: "https://valcho.vercel.app/",
    country: "BG",
  },
  {
    id: "zirve1",
    tag: "shop",
    title: "Zirve1",
    img: "/work/ztest.webp",
    href: "https://www.zirve1.bg/",
    country: "BG",
  },
  {
    id: "emis-cleaning",
    tag: "site",
    title: "Emis Cleaning",
    img: "/work/london.webp",
    href: "https://www.emiscleaning.co.uk/",
    country: "GB",
  },
  {
    id: "santander",
    tag: "site",
    title: "Alp Taxi Santander",
    img: "/work/sndr.webp",
    href: "https://taxisantander.online/",
    country: "ES",
  },
  {
    id: "beca",
    tag: "site",
    title: "BECA Umzugsservice",
    img: "/work/becca.webp",
    href: "https://becaumzug.de/",
    country: "DE",
  },
  {
    id: "amalfi-menu",
    tag: "menu",
    title: "Amalfi",
    img: "/work/corected-amalfi.webp",
    href: "https://www.amalfirestaurant.no/",
    country: "NO",
  },
  {
    id: "chef-resat-menu",
    tag: "menu",
    title: "Chef Resat",
    img: "/work/chefresatcorected.webp",
    href: "https://www.chefresatsofya.com/menu",
    country: "BG",
  },
  {
    id: "pancetita-menu",
    tag: "menu",
    title: "Pizza Pancetita",
    img: "/work/corectedpancetita.webp",
    href: "https://pancetta.vercel.app/",
    country: "NO",
  },
  {
    id: "abi-studio",
    tag: "site",
    title: "Abi Studio",
    img: "/work/abistudio1.webp",
    href: "https://www.abistudiovarna.com/",
    country: "BG",
  },
  {
    id: "nn-bau",
    tag: "site",
    title: "N&N Bau",
    img: "/work/nnbau.webp",
    href: "https://nnbau-sanierung.de/",
    country: "DE",
  },
  {
    id: "metesso",
    tag: "site",
    title: "Metesso",
    img: "/work/metesso1.webp",
    href: "https://www.metesso.com/",
    country: "BG",
  },
  {
    id: "opaka-fits",
    tag: "site",
    title: "Комплекс Фъц",
    img: "/work/opakafits.webp",
    href: "https://opakafits.com/",
    country: "BG",
  },
  {
    id: "taupe",
    tag: "site",
    title: "Taupe",
    img: "/work/taupe1.webp",
    href: "https://www.taupe.bg/",
    country: "BG",
  },
  {
    id: "azteca-site",
    tag: "shop",
    title: "Azteca",
    img: "/work/aztecanew.webp",
    href: "https://azteca-premium.com/",
    country: "BG",
  },
  {
    id: "dudo-group",
    tag: "site",
    title: "Dudo Group",
    img: "/work/dudohip2.webp",
    href: "https://d-group.bg/dudo-stroitelen/index.php",
    country: "BG",
  },
  {
    id: "mig-group",
    tag: "site",
    title: "МИГ Инженеринг Груп",
    img: "/work/geodezi1.webp",
    href: "https://migbulgaria.com/",
    country: "BG",
  },
  {
    id: "het-pitta-loft",
    tag: "site",
    title: "Het Pitta Loft",
    img: "/work/hetpittaloft.webp",
    href: "https://hetpittaloft.be/",
    country: "BE",
  },
  {
    id: "pet-zvezdi",
    tag: "site",
    title: "Пет Звезди",
    img: "/work/petzvezdi.webp",
    href: "https://www.petzvezdiexotics.com",
    country: "BG",
  },
  {
    id: "hh-edelstahl",
    tag: "site",
    title: "H&H Edelstahl",
    img: "/work/edel3.webp",
    href: "https://www.edelstahl-gastro.de",
    country: "DE",
  },
  {
    id: "primasell",
    tag: "site",
    title: "PrimaSell",
    img: "/work/primasell.webp",
    href: "https://primasell.bg/",
    country: "BG",
  },
  {
    id: "szo",
    tag: "shop",
    title: "Security Systems",
    img: "/work/szof1.webp",
    href: "https://www.szo.bg/",
    country: "BG",
  },
  {
    id: "24tours",
    tag: "shop",
    title: "24Tours",
    img: "/work/mototours.webp",
    href: "https://www.24tours.bg/",
    country: "BG",
  },
  {
    id: "hustle-clothing",
    tag: "shop",
    title: "Hustle Clothing",
    img: "/work/hustle2.webp",
    href: "https://hustleclothing.shop/",
    country: "BG",
  },
  {
    id: "shop4home",
    tag: "shop",
    title: "Shop4Home",
    img: "/work/shop111.webp",
    href: "https://shop4home.bg/",
    country: "BG",
  },
  {
    id: "korn-metal",
    tag: "site",
    title: "Korn Metal",
    img: "/work/korn.webp",
    href: "https://www.korn-metal.com/",
    country: "BG",
  },
  {
    id: "hotel-fenix",
    tag: "site",
    title: "Хотел Феникс",
    img: "/work/chepelare.webp",
    href: "https://hotelfenix.vercel.app/",
    country: "BG",
  },
  {
    id: "slapfight",
    tag: "shop",
    title: "SlapFight Bulgaria",
    img: "/work/slapfight2.webp",
    href: "https://slap-fight-bulgaria-nine.vercel.app/",
    country: "BG",
  },
  {
    id: "innenausbau-ahmedov",
    tag: "site",
    title: "Innenausbau Ahmedov",
    img: "/work/innenausbau.webp",
    href: "https://www.innenausbau-ahmedov.de/",
    country: "DE",
  },
];
